### ISSUE TITLE
Bring back delete user endpoint call

### ISSUE THREAD

**Issue by vdiezel** [ospin-web-dev/nexus#117]
Not all users are requesting their own deletion - especially ospin employees. So we want to bring back the deletion endpoint to be triggered by an admin that requests a deletion of a user on their behalf. 

The reason why we haven't deleted a lot of ospin employees yet is because they might own some project specific process that should not be deleted, so we would need to clarify that. 

### Deliverables

- [ ] all admins to create a deletion request for a user
- [ ] create a new endpoint that allows to deactivate a user in cognito (this way we can block a user immediately when we have to, without deleting some resources that we might want to keep in panic); only accessible by an admin

**Comment by lev-leontyev-ospin** [comment]
Question to @felixloeser  - what we gonna do with all the data created to a person whom we are deleting? Mostly a process.

**Comment by felixloeser** [comment]
I think it would be good to give the admins the option to either 
a) delete all processes owned by the person who gets deleted
b) transfer ownership to other user 
c) archive in folder labelled "Archive UserXY"
