### ISSUE TITLE
Add post image method

### ISSUE THREAD

**Issue by DanielSeehausen** [ospin-web-dev/nexus#4]
### Feature Description / Problem Solved by Feature

Add post image method for nexus

---

### Deliverables
- [x] add tests!
- [x] add process.functionalities.image.create  e.g.`API.post("images","processes/:id/functionalities/:id/images)`
- [x] add correct url parameters and body
- [x] update README

**Comment by FelixMZ2018** [comment]
Reopened because of the fixed enpoint and the updated tests
